name: Build App
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "*"

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
          - target: x86_64-apple-darwin
            archive: zip

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: install dependencies (ubuntu only)
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
#      - name: Upload artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: Binary
#          path: |
#            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
#            ${{ steps.compile.outputs.BUILT_CHECKSUM }}